#!/bin/bash
# Key Rotation Script - Execute steps manually

set -e

echo "=== TimeSeal Key Rotation ==="
echo ""
echo "This script guides you through rotating leaked secrets."
echo "Execute each step manually and verify before proceeding."
echo ""

# Step 1: Turnstile
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Rotate Turnstile Secret"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://dash.cloudflare.com/?to=/:account/turnstile"
echo "2. Create NEW widget for timeseal.online"
echo "3. Copy the NEW secret key"
echo "4. Run: echo 'NEW_SECRET_KEY' | npx wrangler secret put TURNSTILE_SECRET_KEY"
echo "5. Copy the NEW site key"
echo "6. Update .env.production:"
echo "   NEXT_PUBLIC_TURNSTILE_SITE_KEY=NEW_SITE_KEY"
echo ""
read -p "Press ENTER when Turnstile rotation is complete..."

# Step 2: Master Key - Deploy old key as fallback
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Deploy Old Master Key as Fallback"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this command:"
echo ""
echo "echo 'I7P7xgYToBXcgS1ZBG8XMt7kWYIxeyUJEB6RfRltphQ=' | npx wrangler secret put MASTER_ENCRYPTION_KEY_OLD"
echo ""
read -p "Press ENTER when old key is deployed..."

# Step 3: Master Key - Generate and deploy new key
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Generate and Deploy New Master Key"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Generate new key:"
NEW_KEY=$(openssl rand -base64 32)
echo "   $NEW_KEY"
echo ""
echo "2. Deploy new key:"
echo "   echo '$NEW_KEY' | npx wrangler secret put MASTER_ENCRYPTION_KEY"
echo ""
read -p "Press ENTER when new key is deployed..."

# Step 4: Deploy code changes
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Deploy Code with Dual-Key Support"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run: npm run deploy:prod"
echo ""
read -p "Press ENTER when deployment is complete..."

# Step 5: Verify
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: Verify Rotation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Check secrets are set:"
echo "   npx wrangler secret list"
echo ""
echo "   Expected output:"
echo "   - MASTER_ENCRYPTION_KEY"
echo "   - MASTER_ENCRYPTION_KEY_OLD"
echo "   - TURNSTILE_SECRET_KEY"
echo ""
echo "2. Test seal creation on https://timeseal.online"
echo "3. Test unlocking existing seals (should work with old key)"
echo ""
read -p "Press ENTER when verification is complete..."

# Step 6: Monitor
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 6: Monitor for 24-48 Hours"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Monitor Cloudflare Workers logs:"
echo "  npx wrangler tail --format pretty"
echo ""
echo "Look for:"
echo "  - 'Using dual-key rotation mode' in logs"
echo "  - No decryption errors"
echo "  - Successful seal unlocks"
echo ""
echo "After 24-48 hours with no issues, proceed to Step 7."
echo ""
read -p "Press ENTER to continue..."

# Step 7: Remove old key
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 7: Remove Old Master Key (After Monitoring)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  WARNING: Only do this after 24-48 hours of successful operation"
echo ""
echo "Run: npx wrangler secret delete MASTER_ENCRYPTION_KEY_OLD"
echo ""
echo "This completes the rotation. All seals now use the new key."
echo ""

echo ""
echo "✅ Rotation guide complete!"
echo ""
echo "Summary:"
echo "  1. ✅ Turnstile secret rotated"
echo "  2. ✅ Old master key deployed as fallback"
echo "  3. ✅ New master key deployed"
echo "  4. ✅ Code deployed with dual-key support"
echo "  5. ✅ Verified rotation working"
echo "  6. ⏳ Monitor for 24-48 hours"
echo "  7. ⏳ Remove old key after monitoring"
echo ""
echo "Update SECURITY-INCIDENT-2025-01-26.md status to RESOLVED when complete."
